import type { ProviderDefinition } from "./types";

export const providerRegistry: ProviderDefinition[] = [
  {
    id: "tavily",
    displayName: "Tavily",
    familyName: "Tavily",
    category: "AI Search",
    icon: "tavily",
    dashboardUrl: "https://app.tavily.com/home",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "brave",
    displayName: "Brave",
    familyName: "Brave",
    category: "AI Search",
    icon: "brave",
    dashboardUrl: "https://api.search.brave.com/app/dashboard",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: true,
  },
  {
    id: "serpapi",
    displayName: "SerpAPI",
    familyName: "SerpAPI",
    category: "AI Search",
    icon: "serpapi",
    dashboardUrl: "https://serpapi.com/dashboard",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "bocha",
    displayName: "Bocha",
    familyName: "Bocha",
    category: "AI Search",
    icon: "bocha",
    dashboardUrl: "https://open.bochaai.com",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "exa",
    displayName: "Exa",
    familyName: "Exa",
    category: "AI Search",
    icon: "exa",
    dashboardUrl: "https://dashboard.exa.ai",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "claude",
    displayName: "Claude",
    familyName: "Anthropic",
    category: "LLM",
    planType: "Pro",
    icon: "claude",
    dashboardUrl: "https://claude.ai/settings/billing",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "codex",
    displayName: "Codex",
    familyName: "OpenAI",
    category: "LLM",
    planType: "Pro",
    icon: "codex",
    dashboardUrl: "https://chatgpt.com",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "kimi",
    displayName: "Kimi",
    familyName: "Moonshot",
    category: "LLM",
    planType: "Membership",
    icon: "kimi",
    dashboardUrl: "https://www.kimi.com/membership/subscription?tab=quota",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
];
